### PR TITLE
✨ add !addbulk command

### PR DESCRIPTION
**Pull request by idinium96**
- Only `sku` or `item` parameter can be used as the item identifying parameter (`name` and `defindex` - no)
- Separate by a new line.
- Format: !addbulk (sku|item)=\<a\>&[[Listing-parameters](https://github.com/TF2Autobot/tf2autobot/wiki/Listing-settings-parameters)]\<Enter (new line)\>\<second and so on\>...
- Example:
```
!addbulk sku=30186;6
sku=5052;6&max=3
item=A Deep Commitment to Purple&intent=buy
item=Totally Boned Pistol (Minimal Wear)&intent=sell&sell.metal=2&group=skin
sku=5052;6&sell.metal=24&buy.metal=23&max=3
sku=5040;6
sku=31129;6
sku=30753;6
sku=30662;6
sku=5076;6
sku=341;6
sku=30994;6
item=A Well Wrapped Hat
sku=610;6
sku=5871;6;c107&max=10&group=crate
sku=30793;6
sku=5077;6
sku=5038;6
sku=31012;6
sku=6522;6;td-1104
```

### CODE REVIEW

**Comment by NeptuniaDenis** [comment]
Yes

**Comment by idinium96** [comment]
> Yes

hurm what?

**Comment by NeptuniaDenis** [comment]
> > Yes
> 
> hurm what?

We need that, we want that, we need yes

**Comment by idinium96** [comment]
Example
image

**Pull request merged**
