### PR TITLE
[development] Docker Build

### PR DESCRIPTION
**Pull request by rennokki**
# The PR content description was copied from https://github.com/TF2Autobot/tf2autobot/pull/374

## Containerization

This PR containerizes the application into a Node.js image for the given tag/commit/latest (for master). The idea behind it is to be able to run it in Docker without issues and orchestrate multiple apps without having to deal with actual servers.

Currently, the PR creates Docker tags for a release, a commit and for the latest master branch. If only releases might suit, I can update the PR to include only the releases. However, it is recommended to keep a history for the GIT SHA tags in order to be able to debug a specific commit in Docker (in case it is needed).

## Versions

The builds are made for the following Node.js versions:

- `15.10-alpine`
- `15.10-buster`
- `15.10-buster-slim`
- `15.10-stretch`
- `15.10-stretch-slim`
- `lts-alpine`

The tag formats are:

- for commits: `[git_sha]-[node_version]`
- for master: `latest-[node_version]`
- for releases: `[git_tag]-[node_version]`

## Secrets

This needs `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` in the repo secrets to be able to push it to the [tf2autobot Docker organization](https://hub.docker.com/orgs/tf2autobot). Please [send a mail](mailto:alex@renoki.org) regarding access to the organization since I've created it for this PR to work.

## Running in Docker

It's a simple as 1-2-3. [For additional envs, `-e` can be used to pass each one.](https://docs.docker.com/engine/reference/commandline/run/)

```bash
$ docker run -e BPTF_ACCESS_TOKEN=some-access-token -e BPTF_API_KEY=some-api-key tfautobot/tfautobot:latest
```

### CODE REVIEW

**Review by arik123 — APPROVED** [review]

**Comment by idinium96** [comment]
@rennokki Thanks for the explanation regarding Docker in general. I've also gathered some information about it from YouTube and some other articles available on the internet.

About the secrets, I will send you an email with my Docker username to possibly transfer the organization that you've created to me and I will setup the secrets for this repository in the repo settings, and after that, sure, this PR will be merged and will be alive once it's merged to the master branch (probably will release v3.5.0 instead of v3.4.9).

**Comment by rennokki** [comment]
@idinium96 I assume the wiki will be modified to include this change.

**Comment by idinium96** [comment]
> @idinium96 I assume the wiki will be modified to include this change.

That's for sure. But since I am not so sure what should be written, I might invite you as a collaborator so that you can add a Wiki page specifically about deploying the bot with Docker.

**Review by idinium96 — APPROVED** [review]
merging to development and let see if the added secrets work.

**Pull request merged**
