### PR TITLE
Use alternative delete if needed

### PR DESCRIPTION
**Pull request by joekiller**
This works around the bot getting into an infinite loop/flaming startup death if the bp mass delete listing endpoint isn't working.

It patches in the currently deleted ListingManager.removeListings function. Once [this pr to add removeListings back](https://github.com/TF2Autobot/node-bptf-listings/pull/9) is accepted, the patching can be removed and just the call can be used.

### CODE REVIEW

**Review by arik123 — APPROVED** [review]

**Comment by idinium96** [comment]
Thank you very much for the PR sir @joekiller! I will look into this very soon. Sorry for the delay.

**Comment by idinium96** [comment]
[This PR](https://github.com/TF2Autobot/node-bptf-listings/pull/9) on @tf2autobot/bptf-listings has been merged and the `removeListings` should be available on the latest version. To prevent any issues, I am appointing sir @joekiller to update this PR accordingly (please do only in your free time, no rush).

**Comment by joekiller** [comment]
Thanks @idinium96 I'll likely hit it this weekend

**Comment by joekiller** [comment]
@idinium96 I have updated the dependency and removed the patching.

also added some abort and retry once behavior with github user content connections sometimes hanging at startup.

**Pull request merged**
