### PR TITLE
prepare v5.1.0

### PR DESCRIPTION
**Pull request by idinium96**
## New stuff
- ✨ Add `!links` command ([#1236](https://github.com/TF2Autobot/tf2autobot/pull/1236))

## Updates/Changes
- ✅ Properly handle inventory fetch ([#1228](https://github.com/TF2Autobot/tf2autobot/pull/1228))
- ✅ Allow Discord bot to chat with non-admin ([#1234](https://github.com/TF2Autobot/tf2autobot/pull/1234), [a39cf2c](https://github.com/TF2Autobot/tf2autobot/pull/1233/commits/a39cf2cfb28fe93e2b154abd46ec64d13f2a5acf), [483dbbe](https://github.com/TF2Autobot/tf2autobot/pull/1233/commits/483dbbee85b50bbdbbec61e8ebdd4d1a0ad2067a))
    - ✨ Add your bot to the TF2Autobot Discord server! Read: [wiki](https://github.com/TF2Autobot/tf2autobot/wiki/Setting-up-Discord-interface#add-your-discord-bot-to-the-tf2autobot-discord-server)
- 🛑 Throw an error if Rep.tf returns invalid response message ([#1235](https://github.com/TF2Autobot/tf2autobot/pull/1235))
- 🔄 Update `!stock` command to include item assetids ([#1237](https://github.com/TF2Autobot/tf2autobot/pull/1237))

## Fixes
- 🐛 Fix html not filtered in log (v5.0.1 extension, [dce09f9](https://github.com/TF2Autobot/tf2autobot/commit/dce09f9b41174b73398db2838624cf07f5f8bbc9), [632793b](https://github.com/TF2Autobot/tf2autobot/commit/632793b7047b5adf8358f7fa72e46d111e5252b3))

### CODE REVIEW

**Comment by RobotoLev** [comment]
Just saw your review request on #1234. Since it was already merged, will leave it here.

As I understand right now, `steamID.type === 0` is being used when we work with quasi-id (which doesn't have actual steam ID). Probably it's good. But I don't understand, do you allow `!message` for Discord non-admin user: on one side, you're blocking it here, but on the other hand, you mentioned it in help.

Also I see two problems with code quality, which I can fix:
* The try-catch duplication here can be easily simplified.
* I have a feeling that this part requires some logging.

**Comment by RobotoLev** [comment]
Also, when I was implementing `redirectAnswerTo` thing, I thought that it might be used for something other in the future, not just for Discord. That's why I inserted checking for it being instance of `DiscordMessage` (`Message` from `discord.js`). I would make something similar here. Right now it's not required, but might be useful in the future.

**Comment by idinium96** [comment]
Thank you for the review.

> Just saw your review request on #1234. Since it was already merged, will leave it here.
> 
> As I understand right now, `steamID.type === 0` is being used when we work with quasi-id (which doesn't have actual steam ID). Probably it's good. But I don't understand, do you allow `!message` for Discord non-admin user: on one side, you're blocking it [here](https://github.com/TF2Autobot/tf2autobot/pull/1234/commits/bb40635fe316ec1b907f5eff831dabd9e19323a0#diff-c1bba1122ce47241dc9ef970e528f4d154196e4996d57d5b98a2ae9410530762R165), but on the other hand, you mentioned it in [help](https://github.com/TF2Autobot/tf2autobot/pull/1234/commits/bb40635fe316ec1b907f5eff831dabd9e19323a0#diff-f7ce90efdca54a78a659457e21351cd2c671db6a37094c9957741a4d6d229c32R26).

Oh yeah, I think I accidentally include `!message` together with other available commands. I will remove it (or you can for sure, just create another pull request for it).


> Also I see two problems with code quality, which I can fix:
> 
> * The try-catch duplication [here](https://github.com/TF2Autobot/tf2autobot/pull/1234/commits/bb40635fe316ec1b907f5eff831dabd9e19323a0#diff-ab5dc63570c5187946d7b73b0ae2d8538b3bff4970ec2ab96216357b2db9410eR70) can be easily simplified.

Oh right, just combine altogether. 👍

> * I have a feeling that [this part](https://github.com/TF2Autobot/tf2autobot/pull/1234/commits/bb40635fe316ec1b907f5eff831dabd9e19323a0#diff-088b8d793fc3d710c799e1931996d48fc4bc7f9c0544f98d7295d9b01ef91570R482) requires some logging.

Not sure why need some logging. This part will just to make sure to ignore command spam on Discord, as far as I understand.

**Comment by idinium96** [comment]
> Also, when I was implementing `redirectAnswerTo` thing, I thought that it might be used for something other in the future, not just for Discord. That's why I inserted checking for it being instance of `DiscordMessage` (`Message` from `discord.js`). I would make something similar [here](https://github.com/TF2Autobot/tf2autobot/pull/1234/commits/bb40635fe316ec1b907f5eff831dabd9e19323a0#diff-088b8d793fc3d710c799e1931996d48fc4bc7f9c0544f98d7295d9b01ef91570R482). Right now it's not required, but might be useful in the future.

Yeah, for now, maybe just stick with this.

**Comment by idinium96** [comment]
Merging...

**Pull request merged**
