### PR TITLE
🔄 update prices.tf auth through message event

### PR DESCRIPTION
**Pull request by idinium96**
Changes in the prices.tf side:
image

### CODE REVIEW

**Comment by joekiller** [comment]
I'll test but the eyeballs say yes

**Review by Nicklason — APPROVED** [review]

**Comment by Nicklason** [comment]
You should also look into using the PRICE_CHANGED event for updating prices, but that can be another PR.

**Comment by joekiller** [comment]
@Nicklason what's the difference between PRICE_UPDATED and PRICE_CHANGED?

**Comment by Nicklason** [comment]
> @Nicklason what's the difference between PRICE_UPDATED and PRICE_CHANGED?

Other than having basically the same name, PRICE_CHANGED is an event emitted when the price has actually changed. PRICE_UPDATED is emitted when an item is priced by the pricer, it could be a price change, but it is usually just the timestamp that is updated.

**Comment by idinium96** [comment]
> > @Nicklason what's the difference between PRICE_UPDATED and PRICE_CHANGED?
> 
> Other than having basically the same name, PRICE_CHANGED is an event emitted when the price has actually changed. PRICE_UPDATED is emitted when an item is priced by the pricer, it could be a price change, but it is usually just the timestamp that is updated.

Ohh nice to know. Yeah maybe in another PR.

Btw, has this not been implemented yet? Still ([pricestf-discord)[https://github.com/TF2Autobot/pricestf-discord]):
image

https://github.com/TF2Autobot/pricestf-discord/blob/a269cdeff72ccd335960f92469c7921554fcb2c6/src/lib/pricer/pricestf/prices-tf-socket-manager.ts#L49-L52

instead of
https://github.com/TF2Autobot/pricestf-discord/blob/a269cdeff72ccd335960f92469c7921554fcb2c6/src/lib/pricer/pricestf/prices-tf-pricer.ts#L117-L130

**Comment by idinium96** [comment]
nvm, will just merge this.

**Pull request merged**
