### PR TITLE
🐛 fix high value items not checking for asset id price

### PR DESCRIPTION
**Pull request by joekiller**
This ensures that high value items are entered into the getHighValue map with the appropriate price key

### CODE REVIEW

**Review by idinium96 — COMMENTED** [review]
Thanks for the PR.
I think this might cause an issue here, but if you have tested and it's all good, then I will merge this soon.
https://github.com/TF2Autobot/tf2autobot/blob/fccc83d8fd02f2b535986ae8e71feaadc9114fdf/src/lib/tools/getHighValue.ts#L71

**Comment by joekiller** [comment]
> Thanks for the PR. I think this might cause an issue here, but if you have tested and it's all good, then I will merge this soon.
> 
> https://github.com/TF2Autobot/tf2autobot/blob/fccc83d8fd02f2b535986ae8e71feaadc9114fdf/src/lib/tools/getHighValue.ts#L71

Yeah it'll blow up if one item isn't on the pricelist while another is. lemme fix it up

**Comment by joekiller** [comment]
also fixed !find not working for pricelist entries with and id

image

**Comment by joekiller** [comment]
okay I squashed and rebased onto development

**Review by idinium96 — APPROVED** [review]
Thank you very much 👍

**Pull request merged**
