### PR TITLE
🐛 fix unable to counter offer with only keys

### PR DESCRIPTION
**Pull request by idinium96**
Every time, as far as I am aware.
image

### CODE REVIEW

**Comment by idinium96** [comment]
Might need to do something with these too:

https://github.com/TF2Autobot/tf2autobot/blob/cfd8bb9c6e78787a8067eb3d0b904c07ce0f70f8/src/classes/Trades.ts#L1052-L1057
https://github.com/TF2Autobot/tf2autobot/blob/cfd8bb9c6e78787a8067eb3d0b904c07ce0f70f8/src/classes/Trades.ts#L1090-L1095

🤔🤔🤔

**Comment by idinium96** [comment]
> The fix I've just committed should also work on trades like this Screenshot_243 Screenshot_244

Woah, thank you! Looks good.

**Comment by idinium96** [comment]
Tested, works with normal items, and yes it still does not work if, for example, I am taking 1 key and only giving 2 ref - the bot will decline the trade.

**Comment by Preport** [comment]
It works just fine on my test bot maybe you don't have enough pure to pay for the key. Or I misunderstood what you're saying.
Screenshot_248
Screenshot_249

**Comment by idinium96** [comment]
Eh weird... I will try again later.

**Comment by idinium96** [comment]
LGTM, merging...

**Pull request merged**
