### PR TITLE
Fixes Error: Cannot log onto steamcommunity...

### PR DESCRIPTION
**Pull request by Preport**
fixes error shown below by making sure we are logged in to steamcommunity first before creating a webSession.

Screenshot_59

### CODE REVIEW

**Comment by idinium96** [comment]
Can you share the full screenshot of that error message?

**Comment by Preport** [comment]
I'm sorry didn't notice I cut it short
Screenshot_60

**Comment by idinium96** [comment]
Thanks.

**Comment by idinium96** [comment]
Reference (from @Preport): https://dev.doctormckay.com/topic/2213-cannot-log-onto-steamcommunitycom-without-first-being-connected-to-steam-network/

**Comment by idinium96** [comment]
btw just a note, since you already have a collaborator role, you can directly clone the main repository and create a new branch from `development` branch, edit, commit, push, and then create a pull request from the newly created branch to the `development` branch.

**Comment by Preport** [comment]
### Didn't knew that was a thing. But I like doing it on my main account and

**Pull request merged**
