### PR TITLE
Refactor Bot.ts

### PR DESCRIPTION
**Pull request by arik123**
Cleaned up Bot.ts

There still is ESLINT error on L336, which could be fixed by making `onPricelist` synchronous.

### CODE REVIEW

**Comment by idinium96** [comment]
I will let sir @joekiller review this since he made these changes.

**Comment by joekiller** [comment]
Hi @arik123 if you bind the way it is setup then each binding is an anonymous function created at that moment of the method call and this can have unintended side effects. For instance if the bot restarts after a crash then you will get double the events. If it crashed again, it would setup triple events. Also because the functions are anonymous if you call removeAllListeners on the socket, it will not be able to remove those functions.

If I am mistaken please let me know. Otherwise I would reject this.

**Comment by arik123** [comment]
> Hi @arik123 if you bind the way it is setup then each binding is an anonymous function created at that moment of the method call and this can have unintended side effects. For instance if the bot restarts after a crash then you will get double the events. If it crashed again, it would setup triple events. Also because the functions are anonymous if you call removeAllListeners on the socket, it will not be able to remove those functions.
> 
> If I am mistaken please let me know. Otherwise I would reject this.

Is there a way how I reproduce this behaviour ? And is there a way how to debug with PM2 ?

**Comment by joekiller** [comment]
I think you could just call !restart several times and then you'll see
duplicate price update events and such.

Sent via mobile

**Comment by idinium96** [comment]
You can put this in your `.env` to see socket activities (credit to @joekiller):
image

**Comment by joekiller** [comment]
Read this: https://medium.com/@DavideRama/removeeventlistener-and-anonymous-functions-ab9dbabd3e7b

**Comment by arik123** [comment]
that should not be a problem, because there does not seem to be any removeListener used

**Comment by arik123** [comment]
I tried restarting the bot, but it did not seem to do anything as it should be.

**Comment by joekiller** [comment]
To shutdown the bot cleanly the socket manager shutdown call uses this.
socket.removeAllListeners()
https://github.com/TF2Autobot/tf2autobot/blob/master/src/classes/BotManager.ts#L244

So it is used.
https://github.com/TF2Autobot/tf2autobot/blob/master/src/classes/MyHandler/SocketManager.ts#L70

One could argue that only a subset of the functions actually need to be
bound to a named instance and I would support that refactor if you want but
anything that gets bound to socket events need to have named instances not
anonymous functions.

Sent via mobile

**Comment by arik123** [comment]
Even if `removeAllListeners()` was somehow unable to remove anonymous listener, if you restart the bot, there should be no problem with double registration of handlers.
Also as far as I can tell, the only two cases, when events are bound to socketManager are [Pricelist](https://github.com/TF2Autobot/tf2autobot/blob/95c61995bd80de23e1bf2754a57e44be23fd7d7b/src/classes/Pricelist.ts#L197) and inside [SocketManager](https://github.com/TF2Autobot/tf2autobot/blob/95c61995bd80de23e1bf2754a57e44be23fd7d7b/src/classes/MyHandler/SocketManager.ts#L47-L61) itself, and in both cases there are no anonymous functions

**Comment by idinium96** [comment]
I'd prefer best practices.

**Comment by arik123** [comment]
and what are the best practises ?

**Comment by idinium96** [comment]
> and what are the best practises?

from the reference provided by @joekiller and his further explanations?

**Comment by joekiller** [comment]
Okay I think we encapsuled the part that could blow up in the socket
manager so I'll pass this

Sent via mobile

**Comment by idinium96** [comment]
alright, now let me see the cause of the error.

**Comment by joekiller** [comment]
But make sure you fix the linting problem which may require a named
reference or some syntax update to bind to the async functions

Sent via mobile

**Review by idinium96 — APPROVED** [review]
Since @joekiller approves, I approve.

**Review by idinium96 — APPROVED** [review]
merging...

**Pull request merged**
