### PR TITLE
Api v2

### PR DESCRIPTION
**Pull request by arik123**
[Requires this pull request to be accepted](https://github.com/TF2Autobot/node-bptf-listings-2/pull/5)
Uses new version of `node-bptf-listings-2` because of no rate limits on updating offers
Merge to master is intentional.

### CODE REVIEW

**Comment by joekiller** [comment]
@arik123 you need to npm install and then commit the updated package-lock.json to make the build pass.

**Comment by arik123** [comment]
As I already wrote, this first needs a PR on `node-bptf-listings-2` accepted.

**Comment by joekiller** [comment]
> As I already wrote

You wrote nothing about fixing the file causing the build fail but a thin prerequisite for merging and left out any explicit follow-up work planned. I'm trying to help this project and do read what is said.

**Comment by arik123** [comment]
I will update `package-lock.json` when the needed module actually exists. I'm gonna make this a draft for now as that makes much more sense.

**Review by idinium96 — APPROVED** [review]
Thank you

**Pull request merged**
