### PR TITLE
[feature] Lighter Docker file by ignoring some files during context copy

### PR DESCRIPTION
**Pull request by rennokki**

### CODE REVIEW

**Comment by idinium96** [comment]
Any update @rennokki?

**Comment by rennokki** [comment]
It seems fine for me. I even forgot this was draft.

**Comment by idinium96** [comment]
> It seems fine for me. I even forgot this was draft.

Ah alright, no problem at all.

**Review by idinium96 — APPROVED** [review]
Thank you very much.

**Pull request merged**
