### PR TITLE
Check bans as class

### PR DESCRIPTION
**Pull request by idinium96**
The problem with previous function based bans check is that, this
https://github.com/TF2Autobot/tf2autobot/blob/a3465225bd7973c502cc1b092e098246765f3bd8/src/lib/bans.ts#L7
and
https://github.com/TF2Autobot/tf2autobot/blob/a3465225bd7973c502cc1b092e098246765f3bd8/src/lib/bans.ts#L19

Might be conflicting when we're processing a lot of offer at the same time.
Doing it in class will make everything isolated, but I am not sure if this will cause a memory leak, or will be managed my GC itself.

### CODE REVIEW

**Comment by idinium96** [comment]
The latest commit [35dde4d](https://github.com/TF2Autobot/tf2autobot/pull/1252/commits/35dde4d6ee124cb52ac05054eec049dc29cae9cd) should help with my concern regarding memory leak, right?

**Comment by RobotoLev** [comment]
In my non-professional opinion, making `v` undefined is unnecessary. GC will collect the object after the function was executed, as it will become unreachable.

**Comment by idinium96** [comment]
> In my non-professional opinion, making `v` undefined is unnecessary. GC will collect the object after the function was executed, as it will become unreachable.

I have the same thought too. Thank you for very much.

**Comment by idinium96** [comment]
Looks good, no significant memory leak, but could be because less trades.

**Comment by idinium96** [comment]
Merging this, I will try implement caching on the next PR.

**Pull request merged**
