### PR TITLE
[feature] Automatic Docker Build

### PR DESCRIPTION
**Pull request by rennokki**
## Containerization

This PR containerizes the application into a Node.js image for the given tag/commit/latest (for master). The idea behind it is to be able to run it in Docker without issues and orchestrate multiple apps without having to deal with actual servers.

Currently, the PR creates Docker tags for a release, a commit and for the latest master branch. If only releases might suit, I can update the PR to include only the releases. However, it is recommended to keep a history for the GIT SHA tags in order to be able to debug a specific commit in Docker (in case it is needed).

## Versions

The builds are made for the following Node.js versions:

- `15.10-alpine`
- `15.10-buster`
- `15.10-buster-slim`
- `15.10-stretch`
- `15.10-stretch-slim`
- `lts-alpine`

The tag formats are:

- for commits: `[git_sha]-[node_version]`
- for master: `latest-[node_version]`
- for releases: `[git_tag]-[node_version]`

## Secrets

This needs `DOCKERHUB_USERNAME` and `DOCKERHUB_TOKEN` in the repo secrets to be able to push it to the [tf2autobot Docker organization](https://hub.docker.com/orgs/tf2autobot). Please [send a mail](mailto:alex@renoki.org) regarding access to the organization since I've created it for this PR to work.

## Running in Docker

It's a simple as 1-2-3. [For additional envs, `-e` can be used to pass each one.](https://docs.docker.com/engine/reference/commandline/run/)

```bash
$ docker run -e BPTF_ACCESS_TOKEN=some-access-token -e BPTF_API_KEY=some-api-key tfautobot/tfautobot:latest
```

### CODE REVIEW

**Comment by rennokki** [comment]
It seems like the secrets aren't pulled from my fork, so I'd suggest to contact me to give access & create tokens for the secrets in Dockerhub in order for this to work.

**Comment by idinium96** [comment]
Thanks for the PR. Let me learn and understand more about Docker first.
Btw, did you created tf2autobot Docker organization under your identity?

**Comment by idinium96** [comment]
Also, I will change the base of this PR to `development` since this is how things work.

**Comment by rennokki** [comment]
@idinium96 At a glance, I have created the Docker organization under my identity before submitting the PR, planning to transfer the ownership. I expected the PR to pull the Github Secrets for the fork, but at this point, I might as well just delete or transfer the organization to any of tfautobot's owners.

### What is Docker

I'm not sure if you're familiar with Docker, but it's a way to "pack and run" bits of OS that will run anywhere, under a special software called "Docker Daemon". Docker Daemon is basically a daemon process that will run the bits of OS (called images) on a server that has Docker installed, without having to deal with provisioning the machine with node & npm, or other bits of software that comes already packed in the image.

The idea behind it is automatization - you can run multiple processes without having to deal with provisioning machines. Anyone can install the Docker CE (community edition) and just plugin `docker run tfbot/tfbot` (with their environment variables) and they will have a fully functioning tfbot.

### Dockerfile & building images

`Dockerfile` is the recipe for the image. It says where to start from, what to run, what to copy, what to expose, what command to run when executing `docker run`. 

[Node.js has free starting images](https://hub.docker.com/_/node/) that you can use to have a Node.js-ready environment for any image that you can create. In this PR, I use multiple versions that will be built for each release/commit/master branch.

Tasks like `npm install` or `npm build` are ran once in the pipeline using `docker build` (which are provided by the docker push action) and just once per build, later on being pushed automatically to the Docker repo, from where they can be later pulled during `docker pull` or `docker run`.

**Comment by rennokki** [comment]
@idinium96 Guess i'll have to update the PR to fit development.

**Pull request closed without merging**
