### PR TITLE
handle change of item assetid(s)

### PR DESCRIPTION
**Pull request by idinium96**
image
Credit: @ZeusJunior

Btw, I am not so sure how to continue this. Anyone that knows, feel free to contribute.
The idea is:
- If an offer was rolled back:
   - update the existing assetid in pricelist to the new one.

### CODE REVIEW

**Comment by idinium96** [comment]
> Items that have rolled back will have a `new_assetid` property you can use

Is it the `new_assetid` or the `rollback_new_assetid`?
The one that I understand is `rollback_new_assetid` for this situation.

**Comment by ZeusJunior** [comment]
Yes, my bad

**Comment by idinium96** [comment]
> Yes, my bad

Alrighty thank you

**Comment by idinium96** [comment]
I assume this will work as intended.
Merging...

**Pull request merged**
