### PR TITLE
Fix for #1348

### PR DESCRIPTION
**Pull request by RobotoLev**
Didn't test it (I'm on phone right now), but it should work. 

The problem is: I committed an old code without testing it properly. Or the last commit in #1348 was conflicting with other ones, can't say for sure right now.

### CODE REVIEW

**Review by idinium96 — APPROVED** [review]
Yep, this resolves the crashes. Thank you very much.

**Comment by idinium96** [comment]
Btw, is it supposed to be `null`? If not, why most of the time it's `null`?

**Comment by RobotoLev** [comment]
Actually, it doesn't do what it should. Just tested, dm chats became unavailable with this commit. Gonna fix it again.

**Comment by idinium96** [comment]
> Actually, it doesn't do what it should. Just tested, dm chats became unavailable with this commit. Gonna fix it again.

Alrighty. 👌

**Pull request merged**
