### PR TITLE
Item stats

### LINKED ISSUE #281: Add item trade statistics
**Is your feature request related to a problem? Please describe.**
Currently, users are unable to determine whether or not specific items are profitable, whether or not specific items buy/sell often, or view general trade data about specific items.

**Describe the feature you'd like**
I propose a new feature - we can call it `!summary`, or perhaps `!sales`, that would provide historic item trade data through Discord Webhook or Steam Chat. It would be called like so: `!summary/sales sku=459;6` or `!summary/sales name=Cosa Nostra Cap`. And it would provide users information like what is seen below:

image
_Note: This information was sourced from https://gladiator.tf/_

This would allow users to see if an item buys/sells well. If it has gone up or down over time. How many (quantity) are being bought/sold. Overall, this would provide users with more granular trade data for items, which they can then use to make informed trading decisions.

**Describe alternatives you've considered**
Using another service (like gladiator.tf) to see trade data. However, this is not pertinent to _your specific bot_, which may change things (such as not having an over-/under-cutter, having more/less capital, etc.).

**Additional context**
I believe that this feature could be implemented by either parsing the already existing `polldata.json`, or by logging item-specific trade history in a separate file, such as `history.json`.

### PR DESCRIPTION
**Pull request by arik123**
Closes #281

### CODE REVIEW

**Comment by idinium96** [comment]
Please pull solved conflict commit

**Comment by idinium96** [comment]
Conflict solved, please pull the changes on your local repo.

**Comment by arik123** [comment]
Could someone please fix the info formating please ?

**Comment by idinium96** [comment]
Latest commit
image

**Pull request merged**
